"""Generates the JP half of the per-region address table from
runtime/include/ps2_addr_list.h: JP addresses (ps2_addr_jp.inc) and the code
words to verify at startup (ps2_addr_words.inc)."""
import json
import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set

from ps2recomp.r5900 import decode

from . import Entry

HEADER = ("/* Generated by python -m regionaddr generate from "
          "runtime/include/ps2_addr_list.h; do not edit. */")
JP_REL = "runtime/include/ps2_addr_jp.inc"
WORDS_REL = "runtime/src/ps2_addr_words.inc"
VERDICTS_REL = "tools/regionaddr/verdicts.json"

VERDICTS = ("same-code", "relocated-only", "changed-verified", "data-same-value",
            "manual-jp", "broken")
CODE_KINDS = ("FUNC", "RET", "CODE")


@dataclass
class Result:
    errors: List[str] = field(default_factory=list)
    needs: List[str] = field(default_factory=list)  # entries without a verdict
    jp_text: str = ""
    words_text: str = ""
    n: int = 0
    by_map: int = 0
    by_verdict: int = 0
    pending: int = 0
    word_checks: int = 0
    word_diffs: int = 0

    def summary(self) -> str:
        return ("regionaddr: %d entries, %d by map, %d by verdict, %d pending, "
                "%d word checks (%d differ)"
                % (self.n, self.by_map, self.by_verdict, self.pending,
                   self.word_checks, self.word_diffs))


def key_of(us: int) -> str:
    return "0x%08X" % us


def load_verdicts(path: str) -> dict:
    with open(path, encoding="utf-8") as fp:
        data = json.load(fp)
    for part in ("addresses", "config", "values"):
        if not isinstance(data.get(part), dict):
            raise ValueError("%s: missing object %r" % (path, part))
    return data


def load_ida_eas(path: str) -> Set[int]:
    with open(path, encoding="utf-8") as fp:
        return {f["ea"] for f in json.load(fp)["functions"]}


def _alloc_sections(elf):
    return [s for s in elf.sections if s.is_alloc and s.size > 0]


def _words(elf, addr: int, n: int) -> List[int]:
    return [elf.word(addr + 4 * i) for i in range(n)]


def _hexw(words) -> str:
    return ", ".join("0x%08Xu" % w for w in words)


def _jal_hits(elf, spans, target: int) -> List[int]:
    """Addresses of `jal target` inside the spans (the delay slot stays in the span)."""
    hits: Set[int] = set()
    for lo, hi in spans:
        for a in range(lo, hi - 4, 4):
            i = decode(elf.word(a), a)
            if i.name == "JAL" and i.target == target:
                hits.add(a)
    return sorted(hits)


def _us_spans(fm) -> List[tuple]:
    if fm.chunks:
        return [(c[0], c[1]) for c in fm.chunks]
    return [(fm.us, fm.us_end)]


def resolve_ret(tr, us: int, jp: Optional[int], call):
    """Prove a RET's JP value from its call. `call` is the decoded US jal at us-8.
    Returns (jp, how, resolved, note); `note` explains an unresolved result."""
    want = tr.func_entry(call.target)
    if want is None:
        return jp, "map", False, "jal target %08X has no JP entry" % call.target
    if jp is not None:
        a = jp - 8
        i = decode(tr.jp_elf.word(a), a)
        if i.name == "JAL" and i.target == want:
            return jp, "map", True, ""
    # The map placed the address wrongly or not at all (changed body): look for the
    # same call in the JP function, but only if the US function has no twin call that
    # would make the pairing ambiguous.
    fm = tr.rmap.function_at(us - 8)
    hits = _jal_hits(tr.jp_elf, tr.jp_spans(us - 8), want)
    twins = _jal_hits(tr.us_elf, _us_spans(fm), call.target) if fm is not None else []
    if len(hits) == 1 and len(twins) == 1:
        return hits[0] + 8, "jal pairing", True, ""
    return jp, "map", False, ("no jal to %08X at JP-8; %d such call(s) in the JP function, "
                              "%d in the US one" % (want, len(hits), len(twins)))


def build(entries: List[Entry], tr, verdicts: dict, ida=None, allow_pending=False) -> Result:
    """Resolve every entry. `ida` is None or (US function eas, JP function eas)."""
    res = Result()
    rmap, us_elf, jp_elf = tr.rmap, tr.us_elf, tr.jp_elf
    addr_verdicts = verdicts.get("addresses", {})
    used: Set[str] = set()
    us_text = next((s for s in us_elf.sections if s.name == ".text"), None)
    us_secs = {s.addr + s.size: s.name for s in _alloc_sections(us_elf)}
    jp_secs = {s.name: s for s in _alloc_sections(jp_elf)}
    jp_by_name: Dict[str, Optional[int]] = {}

    jp_lines = [HEADER, ""]
    words_lines = [HEADER]
    pending_names: List[str] = []

    for e in entries:
        res.n += 1
        us = e.us
        where = "%s (%s, %s)" % (e.name, key_of(us), e.kind)
        in_text = us_text is not None and us_text.addr <= us < us_text.addr + us_text.size
        # An exclusive end belongs to the last byte before it.
        probe = us - 1 if e.kind == "END" else us
        hit = rmap.function_chunk_at(probe)

        # Self-checks of the list itself; these cannot be waived by a verdict.
        bad = None
        if e.kind == "FUNC" and (hit is None or hit[1] != us):
            bad = "not a function or chunk start in the map"
        elif e.kind in ("CODE", "RET") and not in_text:
            bad = "not inside .text"
        elif e.kind == "RET":
            call = decode(us_elf.word(us - 8), us - 8)
            if call.name not in ("JAL", "JALR"):
                bad = "the US word at %s is not jal/jalr" % key_of(us - 8)
        elif e.kind == "DATA" and in_text:
            bad = "inside .text"
        if bad:
            res.errors.append("%s: %s" % (where, bad))
            jp_by_name[e.name] = None
            continue

        # JP value.
        how = "map"
        section_end = False
        if e.kind == "FUNC":
            jp = tr.func_entry(us)
        elif e.kind == "END":
            sec = us_secs.get(us)
            if sec is not None and sec in jp_secs:
                jp = jp_secs[sec].addr + jp_secs[sec].size
                section_end, how = True, "section end"
            else:
                jp = tr.end(us)
        else:
            jp = tr.addr(us)
        # A RET proved by its call needs no verdict, whatever the map says.
        ret_ok, ret_note = False, ""
        if e.kind == "RET":
            if call.name == "JAL":
                jp, how, ret_ok, ret_note = resolve_ret(tr, us, jp, call)
            else:
                ret_note = "jalr call, the target is not checked"

        # Verdict lookup (entries sharing an address are told apart by name).
        key = key_of(us)
        v = addr_verdicts.get(key)
        if v is not None and v.get("name") != e.name:
            v = None
        if v is not None:
            vname = v.get("verdict")
            if vname not in VERDICTS:
                res.errors.append("%s: unknown verdict %r" % (where, vname))
                v = None
            elif vname == "manual-jp" and not ret_ok:
                try:
                    jp = int(v["jp"], 16)
                except (KeyError, TypeError, ValueError):
                    res.errors.append("%s: manual-jp verdict needs a hex jp" % where)
                    v = None

        reasons: List[str] = []
        if jp is None:
            reasons.append("no JP value (%s)" % tr.why(probe))
        if not section_end and not ret_ok:
            r = rmap.range_for(probe)
            if r is None or r.confidence != "high":
                reasons.append("range confidence %s" % (r.confidence if r else "none"))
            if e.kind != "DATA" and hit is not None and hit[0].status != "same":
                reasons.append("function %s is %s" % (hit[0].name, hit[0].status))
        if e.kind == "RET" and not ret_ok:
            reasons.append("RET not proved by its call: " + ret_note)
        if v is not None and v["verdict"] == "manual-jp" and not ret_ok:
            reasons.append("hand-chosen JP value")

        if e.kind == "FUNC" and ida is not None and jp is not None and us in ida[0]:
            if jp not in ida[1]:
                reasons.append("JP %08X is not a function in the JP ida_db" % jp)
        if e.kind == "END" and jp is not None and e.name.endswith("_END"):
            start = jp_by_name.get(e.name[:-4])
            if start is not None and jp <= start:
                reasons.append("JP end %08X is not above JP start %08X" % (jp, start))

        us_w: List[int] = []
        jp_w: List[int] = []
        if e.nwords and e.kind != "END":
            us_w = _words(us_elf, us, e.nwords)
            if jp is not None:
                jp_w = _words(jp_elf, jp, e.nwords)
                res.word_checks += 1
                if jp_w != us_w:
                    res.word_diffs += 1
                    reasons.append("words differ (US %s / JP %s)"
                                   % (_hexw(us_w), _hexw(jp_w)))

        # Verdict gate.
        outcome = "map"
        if reasons:
            if v is None:
                outcome = "pending"
                text = "%s: needs a verdict: %s" % (where, "; ".join(reasons))
                res.needs.append(text)
                if not allow_pending:
                    res.errors.append(text)
            else:
                used.add(key)
                vname = v["verdict"]
                pinned = v.get("jp")
                if vname == "broken":
                    res.errors.append("%s: verdict broken: %s" % (where, v.get("note", "")))
                    outcome = "pending"
                elif vname != "manual-jp" and pinned is not None:
                    try:
                        pin_ok = jp is not None and int(pinned, 16) == jp
                    except (TypeError, ValueError):
                        pin_ok = False
                    if not pin_ok:
                        res.errors.append(
                            "%s: stale verdict, jp %s but the map gives %s"
                            % (where, pinned, "nothing" if jp is None else key_of(jp)))
                        outcome = "pending"
                    else:
                        outcome = "verdict"
                elif jp is None:
                    res.errors.append("%s: verdict %s cannot supply a JP value; use "
                                      "manual-jp" % (where, vname))
                    outcome = "pending"
                else:
                    outcome = "verdict"
                if outcome == "verdict":
                    how = "verdict " + vname
        elif v is not None:
            used.add(key)
            res.errors.append("%s: verdict %s is not needed any more" % (where, v.get("verdict")))

        jp_by_name[e.name] = jp if outcome != "pending" else None
        if outcome == "pending":
            res.pending += 1
            pending_names.append(e.name)
            jp_lines.append("PS2_ADDR_JP(%s, 0x00000000u)  /* PENDING %s */"
                            % (e.name, "; ".join(reasons)))
        else:
            if outcome == "verdict":
                res.by_verdict += 1
            else:
                res.by_map += 1
            jp_lines.append("PS2_ADDR_JP(%s, 0x%08Xu)  /* %s %s */" % (e.name, jp, e.kind, how))

        if e.kind in CODE_KINDS and e.nwords:
            words_lines.append("PS2_WORDS_US(%s, %d, %s)" % (e.name, e.nwords, _hexw(us_w)))
            if outcome != "pending" and jp_w:
                words_lines.append("PS2_WORDS_JP(%s, %d, %s)" % (e.name, e.nwords, _hexw(jp_w)))

    if res.pending:
        jp_lines[1] = "#define PS2_ADDR_JP_PENDING %d" % res.pending
    else:
        del jp_lines[1]

    listed = {key_of(e.us): e for e in entries}
    for key in sorted(addr_verdicts):
        if key in used:
            continue
        e = listed.get(key)
        if e is None:
            res.errors.append("verdict %s: no list entry at this address" % key)
        elif e.name != addr_verdicts[key].get("name"):
            res.errors.append("verdict %s: name %r does not match list entry %s"
                              % (key, addr_verdicts[key].get("name"), e.name))
        else:
            res.errors.append("verdict %s (%s): unused" % (key, e.name))

    res.jp_text = "\n".join(jp_lines) + "\n"
    res.words_text = "\n".join(words_lines) + "\n"
    return res


def _write(path: str, text: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fp:
        fp.write(text)


def _read(path: str) -> Optional[bytes]:
    if not os.path.isfile(path):
        return None
    with open(path, "rb") as fp:
        return fp.read()


def report(res: Result, log=print) -> None:
    for line in res.needs:
        log("needs verdict: " + line)
    for line in res.errors:
        if line not in res.needs:
            log("FAIL " + line)
    log(res.summary())


def _insn_text(elf, addr: int) -> tuple:
    """(word, mnemonic and jump target); unmapped memory reads as a NOP word."""
    word = elf.word(addr)
    i = decode(word, addr)
    text = i.name
    if i.name in ("J", "JAL"):
        text += " %08X" % i.target
    elif i.cat in ("branch", "branchl"):
        text += " ->%08X" % i.btarget
    return word, text


def show_lines(tr, us: int, before: int = 8, after: int = 8,
               jp: Optional[int] = None) -> List[str]:
    """Map facts for `us`, then US and JP instructions side by side. The window is
    counted in instructions; the JP side starts at the translated anchor unless `jp`
    is given (for a hand-picked pairing)."""
    rmap = tr.rmap
    out = []
    hit = rmap.function_chunk_at(us)
    if hit is None:
        out.append("function: none in the map")
    else:
        f = hit[0]
        out.append("function: %s  US %08X-%08X  JP %s  status %s  match %s (conf %.2f, "
                   "sim %.2f)" % (f.name, f.us, f.us_end,
                                  "none" if f.jp is None else "%08X-%08X" % (f.jp, f.jp_end),
                                  f.status, f.method, f.confidence, f.similarity))
    r = rmap.range_for(us)
    out.append("range: " + ("none" if r is None else
               "%08X-%08X delta %+#x %s confidence %s" % (r.us_start, r.us_end, r.delta,
                                                          r.source, r.confidence)))
    mapped = tr.addr(us)
    out.append("why: " + tr.why(us))
    if jp is None:
        jp = mapped
    elif jp != mapped:
        out.append("JP anchor given by hand (the map says %s)"
                   % ("nothing" if mapped is None else "%08X" % mapped))
    out.append("anchor: US %08X  JP %s" % (us, "none" if jp is None else "%08X" % jp))
    out.append("  (> anchor, * decoded text differs)")
    for k in range(-before, after + 1):
        ua = us + 4 * k
        u = _insn_text(tr.us_elf, ua)
        j = None if jp is None else _insn_text(tr.jp_elf, jp + 4 * k)
        ucol = "%08X  %08X %-18s" % (ua, u[0], u[1])
        jcol = "-" if j is None else "%08X  %08X %s" % (jp + 4 * k, j[0], j[1])
        mark = ">" if k == 0 else " "
        if j is not None and u[0] != j[0]:
            mark = ">*" if k == 0 else "*"
        out.append("%-2s %s | %s" % (mark, ucol, jcol))
    return out


def run_show(tr, us: int, before: int, after: int, jp: Optional[int] = None,
             log=print) -> int:
    for line in show_lines(tr, us, before, after, jp):
        log(line.rstrip())
    return 0


def run_generate(entries, tr, verdicts, ida, jp_path, words_path,
                 allow_pending=False, log=print) -> int:
    res = build(entries, tr, verdicts, ida, allow_pending)
    report(res, log)
    if res.errors:
        log("regionaddr: %d failure(s), nothing written" % len(res.errors))
        return 1
    _write(jp_path, res.jp_text)
    _write(words_path, res.words_text)
    if res.pending:
        log("regionaddr: %d entr%s PENDING in %s" % (res.pending,
            "y is" if res.pending == 1 else "ies are", os.path.basename(jp_path)))
    return 0


def run_check(entries, tr, verdicts, ida, jp_path, words_path, log=print) -> int:
    res = build(entries, tr, verdicts, ida, allow_pending=False)
    report(res, log)
    if res.errors:
        return 1
    bad = False
    for path, text in ((jp_path, res.jp_text), (words_path, res.words_text)):
        if _read(path) != text.encode("utf-8"):
            log("regionaddr: %s differs" % os.path.basename(path))
            bad = True
    if bad:
        return 1
    log("regionaddr: generated files are up to date")
    return 0
