"""Generates the JP half of the per-region address table from
runtime/include/ps2_addr_list.h: JP addresses (ps2_addr_jp.inc) and the code
words to verify at startup (ps2_addr_words.inc)."""
import json
import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set

from . import Entry

HEADER = ("/* Generated by python -m regionaddr generate from "
          "runtime/include/ps2_addr_list.h; do not edit. */")
JP_REL = "runtime/include/ps2_addr_jp.inc"
WORDS_REL = "runtime/src/ps2_addr_words.inc"
VERDICTS_REL = "tools/regionaddr/verdicts.json"

VERDICTS = ("same-code", "relocated-only", "changed-verified", "data-same-value",
            "manual-jp", "broken")
CODE_KINDS = ("FUNC", "RET", "CODE")


@dataclass
class Result:
    errors: List[str] = field(default_factory=list)
    needs: List[str] = field(default_factory=list)  # entries without a verdict
    jp_text: str = ""
    words_text: str = ""
    n: int = 0
    by_map: int = 0
    by_verdict: int = 0
    pending: int = 0
    word_checks: int = 0
    word_diffs: int = 0

    def summary(self) -> str:
        return ("regionaddr: %d entries, %d by map, %d by verdict, %d pending, "
                "%d word checks (%d differ)"
                % (self.n, self.by_map, self.by_verdict, self.pending,
                   self.word_checks, self.word_diffs))


def key_of(us: int) -> str:
    return "0x%08X" % us


def load_verdicts(path: str) -> dict:
    with open(path, encoding="utf-8") as fp:
        data = json.load(fp)
    for part in ("addresses", "config", "values"):
        if not isinstance(data.get(part), dict):
            raise ValueError("%s: missing object %r" % (path, part))
    return data


def load_ida_eas(path: str) -> Set[int]:
    with open(path, encoding="utf-8") as fp:
        return {f["ea"] for f in json.load(fp)["functions"]}


def _alloc_sections(elf):
    return [s for s in elf.sections if s.is_alloc and s.size > 0]


def _words(elf, addr: int, n: int) -> List[int]:
    return [elf.word(addr + 4 * i) for i in range(n)]


def _hexw(words) -> str:
    return ", ".join("0x%08Xu" % w for w in words)


def build(entries: List[Entry], tr, verdicts: dict, ida=None, allow_pending=False) -> Result:
    """Resolve every entry. `ida` is None or (US function eas, JP function eas)."""
    res = Result()
    rmap, us_elf, jp_elf = tr.rmap, tr.us_elf, tr.jp_elf
    addr_verdicts = verdicts.get("addresses", {})
    used: Set[str] = set()
    us_text = next((s for s in us_elf.sections if s.name == ".text"), None)
    us_secs = {s.addr + s.size: s.name for s in _alloc_sections(us_elf)}
    jp_secs = {s.name: s for s in _alloc_sections(jp_elf)}
    jp_by_name: Dict[str, Optional[int]] = {}

    jp_lines = [HEADER, ""]
    words_lines = [HEADER]
    pending_names: List[str] = []

    for e in entries:
        res.n += 1
        us = e.us
        where = "%s (%s, %s)" % (e.name, key_of(us), e.kind)
        in_text = us_text is not None and us_text.addr <= us < us_text.addr + us_text.size
        # An exclusive end belongs to the last byte before it.
        probe = us - 1 if e.kind == "END" else us
        hit = rmap.function_chunk_at(probe)

        # Self-checks of the list itself; these cannot be waived by a verdict.
        bad = None
        if e.kind == "FUNC" and (hit is None or hit[1] != us):
            bad = "not a function or chunk start in the map"
        elif e.kind in ("CODE", "RET") and not in_text:
            bad = "not inside .text"
        elif e.kind == "DATA" and in_text:
            bad = "inside .text"
        if bad:
            res.errors.append("%s: %s" % (where, bad))
            jp_by_name[e.name] = None
            continue

        # JP value.
        how = "map"
        section_end = False
        if e.kind == "FUNC":
            jp = tr.func_entry(us)
        elif e.kind == "END":
            sec = us_secs.get(us)
            if sec is not None and sec in jp_secs:
                jp = jp_secs[sec].addr + jp_secs[sec].size
                section_end, how = True, "section end"
            else:
                jp = tr.end(us)
        else:
            jp = tr.addr(us)

        # Verdict lookup (entries sharing an address are told apart by name).
        key = key_of(us)
        v = addr_verdicts.get(key)
        if v is not None and v.get("name") != e.name:
            v = None
        if v is not None:
            vname = v.get("verdict")
            if vname not in VERDICTS:
                res.errors.append("%s: unknown verdict %r" % (where, vname))
                v = None
            elif vname == "manual-jp":
                try:
                    jp = int(v["jp"], 16)
                except (KeyError, TypeError, ValueError):
                    res.errors.append("%s: manual-jp verdict needs a hex jp" % where)
                    v = None

        reasons: List[str] = []
        if jp is None:
            reasons.append("no JP value (%s)" % tr.why(probe))
        if not section_end:
            r = rmap.range_for(probe)
            if r is None or r.confidence != "high":
                reasons.append("range confidence %s" % (r.confidence if r else "none"))
            if e.kind != "DATA" and hit is not None and hit[0].status != "same":
                reasons.append("function %s is %s" % (hit[0].name, hit[0].status))
        if e.kind == "RET":
            reasons.append("RET jal pairing is not checked yet")
        if v is not None and v["verdict"] == "manual-jp":
            reasons.append("hand-chosen JP value")

        if e.kind == "FUNC" and ida is not None and jp is not None and us in ida[0]:
            if jp not in ida[1]:
                reasons.append("JP %08X is not a function in the JP ida_db" % jp)
        if e.kind == "END" and jp is not None and e.name.endswith("_END"):
            start = jp_by_name.get(e.name[:-4])
            if start is not None and jp <= start:
                reasons.append("JP end %08X is not above JP start %08X" % (jp, start))

        us_w: List[int] = []
        jp_w: List[int] = []
        if e.nwords and e.kind != "END":
            us_w = _words(us_elf, us, e.nwords)
            if jp is not None:
                jp_w = _words(jp_elf, jp, e.nwords)
                res.word_checks += 1
                if jp_w != us_w:
                    res.word_diffs += 1
                    reasons.append("words differ (US %s / JP %s)"
                                   % (_hexw(us_w), _hexw(jp_w)))

        # Verdict gate.
        outcome = "map"
        if reasons:
            if v is None:
                outcome = "pending"
                text = "%s: needs a verdict: %s" % (where, "; ".join(reasons))
                res.needs.append(text)
                if not allow_pending:
                    res.errors.append(text)
            else:
                used.add(key)
                vname = v["verdict"]
                pinned = v.get("jp")
                if vname == "broken":
                    res.errors.append("%s: verdict broken: %s" % (where, v.get("note", "")))
                    outcome = "pending"
                elif vname != "manual-jp" and pinned is not None:
                    try:
                        pin_ok = jp is not None and int(pinned, 16) == jp
                    except (TypeError, ValueError):
                        pin_ok = False
                    if not pin_ok:
                        res.errors.append(
                            "%s: stale verdict, jp %s but the map gives %s"
                            % (where, pinned, "nothing" if jp is None else key_of(jp)))
                        outcome = "pending"
                    else:
                        outcome = "verdict"
                elif jp is None:
                    res.errors.append("%s: verdict %s cannot supply a JP value; use "
                                      "manual-jp" % (where, vname))
                    outcome = "pending"
                else:
                    outcome = "verdict"
                if outcome == "verdict":
                    how = "verdict " + vname
        elif v is not None:
            used.add(key)
            res.errors.append("%s: verdict %s is not needed any more" % (where, v.get("verdict")))

        jp_by_name[e.name] = jp if outcome != "pending" else None
        if outcome == "pending":
            res.pending += 1
            pending_names.append(e.name)
            jp_lines.append("PS2_ADDR_JP(%s, 0x00000000u)  /* PENDING %s */"
                            % (e.name, "; ".join(reasons)))
        else:
            if outcome == "verdict":
                res.by_verdict += 1
            else:
                res.by_map += 1
            jp_lines.append("PS2_ADDR_JP(%s, 0x%08Xu)  /* %s %s */" % (e.name, jp, e.kind, how))

        if e.kind in CODE_KINDS and e.nwords:
            words_lines.append("PS2_WORDS_US(%s, %d, %s)" % (e.name, e.nwords, _hexw(us_w)))
            if outcome != "pending" and jp_w:
                words_lines.append("PS2_WORDS_JP(%s, %d, %s)" % (e.name, e.nwords, _hexw(jp_w)))

    if res.pending:
        jp_lines[1] = "#define PS2_ADDR_JP_PENDING %d" % res.pending
    else:
        del jp_lines[1]

    listed = {key_of(e.us): e for e in entries}
    for key in sorted(addr_verdicts):
        if key in used:
            continue
        e = listed.get(key)
        if e is None:
            res.errors.append("verdict %s: no list entry at this address" % key)
        elif e.name != addr_verdicts[key].get("name"):
            res.errors.append("verdict %s: name %r does not match list entry %s"
                              % (key, addr_verdicts[key].get("name"), e.name))
        else:
            res.errors.append("verdict %s (%s): unused" % (key, e.name))

    res.jp_text = "\n".join(jp_lines) + "\n"
    res.words_text = "\n".join(words_lines) + "\n"
    return res


def _write(path: str, text: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fp:
        fp.write(text)


def _read(path: str) -> Optional[bytes]:
    if not os.path.isfile(path):
        return None
    with open(path, "rb") as fp:
        return fp.read()


def report(res: Result, log=print) -> None:
    for line in res.needs:
        log("needs verdict: " + line)
    for line in res.errors:
        if line not in res.needs:
            log("FAIL " + line)
    log(res.summary())


def run_generate(entries, tr, verdicts, ida, jp_path, words_path,
                 allow_pending=False, log=print) -> int:
    res = build(entries, tr, verdicts, ida, allow_pending)
    report(res, log)
    if res.errors:
        log("regionaddr: %d failure(s), nothing written" % len(res.errors))
        return 1
    _write(jp_path, res.jp_text)
    _write(words_path, res.words_text)
    if res.pending:
        log("regionaddr: %d entr%s PENDING in %s" % (res.pending,
            "y is" if res.pending == 1 else "ies are", os.path.basename(jp_path)))
    return 0


def run_check(entries, tr, verdicts, ida, jp_path, words_path, log=print) -> int:
    res = build(entries, tr, verdicts, ida, allow_pending=False)
    report(res, log)
    if res.errors:
        return 1
    bad = False
    for path, text in ((jp_path, res.jp_text), (words_path, res.words_text)):
        if _read(path) != text.encode("utf-8"):
            log("regionaddr: %s differs" % os.path.basename(path))
            bad = True
    if bad:
        return 1
    log("regionaddr: generated files are up to date")
    return 0
