import argparse
import os
import sys

if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    __package__ = "modkit"

from .pac import Archive, Names, open_disc, TAIL_START, TAIL_SHIFT


def main(argv=None):
    ap = argparse.ArgumentParser(prog="modkit.export_names")
    ap.add_argument("--disc", required=True)
    ap.add_argument("--names", required=True, help="datapack.bin")
    ap.add_argument("-o", "--out", required=True)
    args = ap.parse_args(argv)

    ar = open_disc(args.disc)
    nm = Names(args.names)
    lines, named, slipped, files = [], 0, [], 0
    for i in range(ar.count):
        count = ar.file_count(i)
        names = nm.names_for(i, expect=count)
        if names is None:
            if count:
                slipped.append((i, count))
            continue
        named += 1
        for k, name in enumerate(names):
            lines.append("%d %d %s" % (i, k, name))
            files += 1

    with open(args.out, "w", encoding="utf-8", newline="\n") as fp:
        fp.write("# DATA.PAC name table, generated by modkit.export_names.\n")
        fp.write("# <member> <index> <name>\n")
        fp.write("# %d of %d members resolved, %d files.\n"
                 % (named, ar.count, files))
        fp.write("# Mapping: member i -> index group i below %d, group i+%d "
                 "from there on.\n" % (TAIL_START, TAIL_SHIFT))
        if slipped:
            fp.write("# Unresolved members (the index disagrees on how many "
                     "files they hold):\n")
            for i, c in slipped:
                fp.write("#   member %d holds %d files\n" % (i, c))
        fp.write("# members: %d\n" % ar.count)
        for line in lines:
            fp.write(line + "\n")
    ar.close()
    print("wrote %s: %d files across %d of %d members (%d unresolved)"
          % (args.out, files, named, ar.count, len(slipped)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
